TrackermanServer/config/routes.rb
# == Route Map
#
#                      Prefix Verb   URI Pattern                            Controller#Action
#            new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#                user_session POST   /users/sign_in(.:format)               devise/sessions#create
#        destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#               user_password POST   /users/password(.:format)              devise/passwords#create
#           new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#          edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                             PATCH  /users/password(.:format)              devise/passwords#update
#                             PUT    /users/password(.:format)              devise/passwords#update
#    cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#           user_registration POST   /users(.:format)                       devise/registrations#create
#       new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#      edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                             PATCH  /users(.:format)                       devise/registrations#update
#                             PUT    /users(.:format)                       devise/registrations#update
#                             DELETE /users(.:format)                       devise/registrations#destroy
#                      places GET    /places(.:format)                      places#index
#                             POST   /places(.:format)                      places#create
#                   new_place GET    /places/new(.:format)                  places#new
#                  edit_place GET    /places/:id/edit(.:format)             places#edit
#                       place GET    /places/:id(.:format)                  places#show
#                             PATCH  /places/:id(.:format)                  places#update
#                             PUT    /places/:id(.:format)                  places#update
#                             DELETE /places/:id(.:format)                  places#destroy
#                       areas GET    /areas(.:format)                       areas#index
#                             POST   /areas(.:format)                       areas#create
#                    new_area GET    /areas/new(.:format)                   areas#new
#                   edit_area GET    /areas/:id/edit(.:format)              areas#edit
#                        area GET    /areas/:id(.:format)                   areas#show
#                             PATCH  /areas/:id(.:format)                   areas#update
#                             PUT    /areas/:id(.:format)                   areas#update
#                             DELETE /areas/:id(.:format)                   areas#destroy
#                       zones GET    /zones(.:format)                       zones#index
#                             POST   /zones(.:format)                       zones#create
#                    new_zone GET    /zones/new(.:format)                   zones#new
#                   edit_zone GET    /zones/:id/edit(.:format)              zones#edit
#                        zone GET    /zones/:id(.:format)                   zones#show
#                             PATCH  /zones/:id(.:format)                   zones#update
#                             PUT    /zones/:id(.:format)                   zones#update
#                             DELETE /zones/:id(.:format)                   zones#destroy
#                             GET    /places(.:format)                      places#index
#                             POST   /places(.:format)                      places#create
#                             GET    /places/new(.:format)                  places#new
#                             GET    /places/:id/edit(.:format)             places#edit
#                             GET    /places/:id(.:format)                  places#show
#                             PATCH  /places/:id(.:format)                  places#update
#                             PUT    /places/:id(.:format)                  places#update
#                             DELETE /places/:id(.:format)                  places#destroy
#                   treasures GET    /treasures(.:format)                   treasures#index
#                             POST   /treasures(.:format)                   treasures#create
#                new_treasure GET    /treasures/new(.:format)               treasures#new
#               edit_treasure GET    /treasures/:id/edit(.:format)          treasures#edit
#                    treasure GET    /treasures/:id(.:format)               treasures#show
#                             PATCH  /treasures/:id(.:format)               treasures#update
#                             PUT    /treasures/:id(.:format)               treasures#update
#                             DELETE /treasures/:id(.:format)               treasures#destroy
#          api_v1_get_players GET    /api/v1/get_players(.:format)          api/v1/service#get_players
#            api_v1_get_zones GET    /api/v1/get_zones(.:format)            api/v1/service#get_zones
#        api_v1_create_player POST   /api/v1/create_player(.:format)        api/v1/service#create_player
#              api_v1_add_pos POST   /api/v1/add_pos(.:format)              api/v1/service#add_pos
#             api_v1_ping_ios POST   /api/v1/ping_ios(.:format)             api/v1/service#ping_ios
#         api_v1_ping_android GET    /api/v1/ping_android(.:format)         api/v1/service#ping_android
# api_v1_get_treasures_within GET    /api/v1/get_treasures_within(.:format) api/v1/service#get_treasures_within
#             api_v1_sessions POST   /api/v1/sessions(.:format)             api/v1/sessions#create
#                     players GET    /players(.:format)                     players#index
#                 show_player GET    /player/:id(.:format)                  players#show
#                        root GET    /                                      home#index
#

Rails.application.routes.draw do

  devise_for :users

  resources :places
  resources :areas

  resources :zones
  resources :places
  resources :treasures

  # we use Devise...
  #get    'signup'  => 'users#new'
  #get    'login'   => 'sessions#new'
  #post   'login'   => 'sessions#create'
  #delete 'logout'  => 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      get  'get_players'            => 'service#get_players'
      get  'get_zones'              => 'service#get_zones'
      post 'create_player'          => 'service#create_player'
      post 'add_pos'                => 'service#add_pos'

      post 'ping_ios'               => 'service#ping_ios'
      get  'ping_android'           => 'service#ping_android'
      get  'get_treasures_within'   => 'service#get_treasures_within'

      resources :sessions, only: [:create]
    end

  end


  get  '/players'               => 'players#index'
  get  '/player/:id'            => 'players#show', :as => 'show_player'

  root :to => 'home#index'


  # Catch invalid routes!
  #match ':not_found' => 'my_controller#index',
   #     :constraints => { :not_found => /.*/ }

  #If you only want to redirect, nothing more, you could do this instead (again, at the bottom):
  #match ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }

end

TrackermanServer/app/models/zone.rb
# == Schema Information
#
# Table name: zones
#
#  id          :integer          not null, primary key
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  area_id     :integer
#  json_points :text
#

class Zone < ActiveRecord::Base
	has_many :polygons
	accepts_nested_attributes_for :polygons
end

TrackermanServer/app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = Zone.all
    puts @zones.to_json

    gon.zones = []
    @zones.each do |z|
      puts "START:" + z.json_points + ":END"
      gon.zones.push JSON.parse(z.json_points)     # json string
    end

  end

  # GET /zones/1
  # GET /zones/1.json
  def show
  end

  # GET /zones/new
  def new
    # needed??
    @zones = Zone.all
    gon.zones = @zones

    @zone = Zone.new
    gon.zone = @zone
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create

    puts "PARAMS=" + zone_params.to_s

    @zone = Zone.new(zone_params)

    respond_to do |format|
      if @zone.save
        puts "----------- SAVE OK ------------------"
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        puts "----------- ERROR ------------------"
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to edit_zone_path(@zone), notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end

	#redirect_to edit_zone_path(@zone)
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy

	  puts "controller destroy here!"
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
	  puts "controller destroy finished here!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find(params[:id])
      gon.zone = @zone

      #
      # TMP HACK!
      #
      @zones = Zone.all
      gon.zones = @zones
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:name, :json_points)
    end
end

#
#def rundatum_params
#  params.require(:rundatum).permit(
#      :material, :company_id, :material_density, :feed_moisture, :date,
#      :building, :machine, :material_weight, :time_mins, :rate_lb_hr,
#      :mill_amps, :class_amps, :mill_liner,
#      :beater_plate_size, :mill_rpm, :class_rpm, :feeder_type,
#      :feeder_setting, :feeder_aug_diameter, :tlgs_set, :air_pressure,
#      :temp_mill_out, :temp_prod_out, :temp_ambient,
#
#      { materials_attributes:
#            [:id, :name, :density, :msds_url, :moisture, :notes, :_destroy,
#              { particle_sizes_attributes: [:id, :screen, :percent_through, :percent_retained, :_destroy]
#              }
#            ]
#      }
#  )
#end

TrackermanServer/app/helpers/zones_helper.rb
module ZonesHelper
end

TrackermanServer/app/views/zones/_form.html.erb
<%= simple_nested_form_for @zone, html: { class: 'form-horizontal' },

    wrapper: :horizontal_form,
    wrapper_mappings: {
      check_boxes: :horizontal_radio_and_checkboxes,
      radio_buttons: :horizontal_radio_and_checkboxes,
      file: :horizontal_file_input,
      boolean: :horizontal_boolean
    } do |f| %>

  <%= f.error_notification %>

  <%= f.input :name, :placeholder => 'Name' %>

    <%= f.fields_for :polygons do |builder| %>
        <%= render "polygon_fields", :f => builder %>
        <%= builder.link_to_remove "Remove" %>
    <% end %>
    <%= f.link_to_add "Add a segment", :polygons %>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

TrackermanServer/app/views/zones/_polygon_fields.html.erb
<%= f.input_field :json_points %>

TrackermanServer/app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form' %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

TrackermanServer/app/views/zones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zoner</h1>

<table class="table table-bordered table-hovered table-condensed">
  <thead>
    <tr>
      <th>Zon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.name %></td>
        <td><%= zone.json_points %></td>
<!--        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>   -->
        <td id="<%= zone.name %>" class="zone_name">Show</td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<script>
  $('.zone_name').click(function(evt) {
    // alert($(this).attr('id'));
    var id=$(this).attr('id');
    // alert(typeof(gon.zones));
    for (i=0; i<gon.zones.length; i++) {
      // alert(gon.zones[i].name);
    }
  });

</script>

<div id="control">
  <button id="start">START</button>
  <input id="name"></input>
  <button id="stop" >STOP</button>
  <button id="save" >SAVE</button>
</div>

<div id="map">

</div>

<style>
  #map {
    width: 100%;
    height: 1000px;
  }
</style>


<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLrXVDgIBkFlSsRYbzyxKDce9pRIEaekY&callback=initMap" >
</script>

<script>
  var started = false;
  var polyline;
  var points = [];
  var map;

  /*  -------------------------------------------------

      -------------------------------------------------
   */
  function initMap() {

    var myLatLng = {lat: 60.644, lng: 17.000};
    var mapDiv = document.getElementById('map');

    map = new google.maps.Map(mapDiv, {
      center: myLatLng,
      mapTypeId: google.maps.MapTypeId.SATELLITE,
      zoom: 15
    });

    /*  -----------------------------------------------
        MAP CLICK EVENT HANDLER
        -----------------------------------------------
     */
    map.addListener('click', function(event) {
      if (started) {
        var path = polyline.getPath();
        path.push(event.latLng);

        points.push(event.latLng);
      }
    });

    /*  -----------------------------------------------
        START BUTTON EVENT HANDLER
        -----------------------------------------------
     */
    $("#start").click(function() {
      started = true;

      polyline = new google.maps.Polyline({
        strokeColor: '#000000',
        strokeOpacity: 1.0,
        strokeWeight: 3
      });
      polyline.setMap(map);
    });

    /*  -----------------------------------------------
        STOP BUTTON EVENT HANDLER
        -----------------------------------------------
     */
    $("#stop").click(function() {
      started = false;

      // Construct the polygon.
      var z = new google.maps.Polygon({
        paths: points,
        strokeColor: '#000000',
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: '#FF0000',
        fillOpacity: 0.25,
        editable: true
      });

      polyline.setMap(null);
      z.setMap(map);

      points = [];
    });

    /*  -----------------------------------------------
        SAVE BUTTON EVENT HANDLER
        -----------------------------------------------
     */
    $("#save").click(function() {
      // save the ZONE
      var str = JSON.stringify(polyline.getPath().getArray());
      var name = $("#name").val();
      $.post("/zones", {
        zone: {
          name: name,
          json_points: str
        }
      });
    });

    drawZones(gon.zones);

  }

  function drawZones(points) {

    // Construct the polygon.
    var z = new google.maps.Polygon({
      paths: points,
      strokeColor: '#000000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.25,
      editable: true
    });

    z.setMap(map);
  }

</script>

TrackermanServer/app/views/zones/new.html.erb
<h1>New Zone</h1>

<%= render 'form' %>

<%= link_to 'Back', zones_path %>

TrackermanServer/app/views/zones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zone.name %>
</p>

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>