TrackermanServer/config/routes.rb
# == Route Map
#
#                      Prefix Verb   URI Pattern                            Controller#Action
#            new_user_session GET    /users/sign_in(.:format)               devise/sessions#new
#                user_session POST   /users/sign_in(.:format)               devise/sessions#create
#        destroy_user_session DELETE /users/sign_out(.:format)              devise/sessions#destroy
#               user_password POST   /users/password(.:format)              devise/passwords#create
#           new_user_password GET    /users/password/new(.:format)          devise/passwords#new
#          edit_user_password GET    /users/password/edit(.:format)         devise/passwords#edit
#                             PATCH  /users/password(.:format)              devise/passwords#update
#                             PUT    /users/password(.:format)              devise/passwords#update
#    cancel_user_registration GET    /users/cancel(.:format)                devise/registrations#cancel
#           user_registration POST   /users(.:format)                       devise/registrations#create
#       new_user_registration GET    /users/sign_up(.:format)               devise/registrations#new
#      edit_user_registration GET    /users/edit(.:format)                  devise/registrations#edit
#                             PATCH  /users(.:format)                       devise/registrations#update
#                             PUT    /users(.:format)                       devise/registrations#update
#                             DELETE /users(.:format)                       devise/registrations#destroy
#                      places GET    /places(.:format)                      places#index
#                             POST   /places(.:format)                      places#create
#                   new_place GET    /places/new(.:format)                  places#new
#                  edit_place GET    /places/:id/edit(.:format)             places#edit
#                       place GET    /places/:id(.:format)                  places#show
#                             PATCH  /places/:id(.:format)                  places#update
#                             PUT    /places/:id(.:format)                  places#update
#                             DELETE /places/:id(.:format)                  places#destroy
#                       areas GET    /areas(.:format)                       areas#index
#                             POST   /areas(.:format)                       areas#create
#                    new_area GET    /areas/new(.:format)                   areas#new
#                   edit_area GET    /areas/:id/edit(.:format)              areas#edit
#                        area GET    /areas/:id(.:format)                   areas#show
#                             PATCH  /areas/:id(.:format)                   areas#update
#                             PUT    /areas/:id(.:format)                   areas#update
#                             DELETE /areas/:id(.:format)                   areas#destroy
#                       zones GET    /zones(.:format)                       zones#index
#                             POST   /zones(.:format)                       zones#create
#                    new_zone GET    /zones/new(.:format)                   zones#new
#                   edit_zone GET    /zones/:id/edit(.:format)              zones#edit
#                        zone GET    /zones/:id(.:format)                   zones#show
#                             PATCH  /zones/:id(.:format)                   zones#update
#                             PUT    /zones/:id(.:format)                   zones#update
#                             DELETE /zones/:id(.:format)                   zones#destroy
#                             GET    /places(.:format)                      places#index
#                             POST   /places(.:format)                      places#create
#                             GET    /places/new(.:format)                  places#new
#                             GET    /places/:id/edit(.:format)             places#edit
#                             GET    /places/:id(.:format)                  places#show
#                             PATCH  /places/:id(.:format)                  places#update
#                             PUT    /places/:id(.:format)                  places#update
#                             DELETE /places/:id(.:format)                  places#destroy
#                   treasures GET    /treasures(.:format)                   treasures#index
#                             POST   /treasures(.:format)                   treasures#create
#                new_treasure GET    /treasures/new(.:format)               treasures#new
#               edit_treasure GET    /treasures/:id/edit(.:format)          treasures#edit
#                    treasure GET    /treasures/:id(.:format)               treasures#show
#                             PATCH  /treasures/:id(.:format)               treasures#update
#                             PUT    /treasures/:id(.:format)               treasures#update
#                             DELETE /treasures/:id(.:format)               treasures#destroy
#          api_v1_get_players GET    /api/v1/get_players(.:format)          api/v1/service#get_players
#            api_v1_get_zones GET    /api/v1/get_zones(.:format)            api/v1/service#get_zones
#        api_v1_create_player POST   /api/v1/create_player(.:format)        api/v1/service#create_player
#              api_v1_add_pos POST   /api/v1/add_pos(.:format)              api/v1/service#add_pos
#             api_v1_ping_ios POST   /api/v1/ping_ios(.:format)             api/v1/service#ping_ios
#         api_v1_ping_android GET    /api/v1/ping_android(.:format)         api/v1/service#ping_android
# api_v1_get_treasures_within GET    /api/v1/get_treasures_within(.:format) api/v1/service#get_treasures_within
#             api_v1_sessions POST   /api/v1/sessions(.:format)             api/v1/sessions#create
#                     players GET    /players(.:format)                     players#index
#                 show_player GET    /player/:id(.:format)                  players#show
#                        root GET    /                                      home#index
#

Rails.application.routes.draw do

  devise_for :users

  resources :places
  resources :areas

  resources :zones
  resources :places
  resources :treasures

  # we use Devise...
  #get    'signup'  => 'users#new'
  #get    'login'   => 'sessions#new'
  #post   'login'   => 'sessions#create'
  #delete 'logout'  => 'sessions#destroy'

  namespace :api do
    namespace :v1 do
      get  'get_players'            => 'service#get_players'
      get  'get_zones'              => 'service#get_zones'
      post 'create_player'          => 'service#create_player'
      post 'add_pos'                => 'service#add_pos'

      post 'ping_ios'               => 'service#ping_ios'
      get  'ping_android'           => 'service#ping_android'
      get  'get_treasures_within'   => 'service#get_treasures_within'

      resources :sessions, only: [:create]
    end

  end


  get  '/players'               => 'players#index'
  get  '/player/:id'            => 'players#show', :as => 'show_player'

  root :to => 'home#index'


  # Catch invalid routes!
  #match ':not_found' => 'my_controller#index',
   #     :constraints => { :not_found => /.*/ }

  #If you only want to redirect, nothing more, you could do this instead (again, at the bottom):
  #match ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }

end

TrackermanServer/app/models/treasure.rb
# == Schema Information
#
# Table name: treasures
#
#  id         :integer          not null, primary key
#  name       :string
#  lat        :decimal(, )
#  lng        :decimal(, )
#  value      :integer
#  start      :datetime
#  stop       :datetime
#  num_takers :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Treasure < ActiveRecord::Base
end

TrackermanServer/app/controllers/treasures_controller.rb
class TreasuresController < ApplicationController
  before_action :set_treasure, only: [:show, :edit, :update, :destroy]

  def broadcast (treasure, action)

	  puts "Sending Treasure Update!"
	  Pusher.trigger('treasure_channel',
	                 'treasure', {
		                object: treasure.to_json,
		                message: action
	                 })

  end

  # GET /treasures
  # GET /treasures.json
  def index
    @treasures = Treasure.all
	gon.treasures = Treasure.all
  end

  # GET /treasures/1
  # GET /treasures/1.json
  def show
  end

  # GET /treasures/new
  def new
    @treasure = Treasure.new
  end

  # GET /treasures/1/edit
  def edit
  end

  # POST /treasures
  # POST /treasures.json
  def create
    @treasure = Treasure.new(treasure_params)

    respond_to do |format|
      if @treasure.save
        format.html { redirect_to @treasure, notice: 'Treasure was successfully created.' }
        format.json { render :show, status: :created, location: @treasure }

		#broadcast @treasure, "created"
      else
        format.html { render :new }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /treasures/1
  # PATCH/PUT /treasures/1.json
  def update
    respond_to do |format|
      if @treasure.update(treasure_params)
        format.html { redirect_to @treasure, notice: 'Treasure was successfully updated.' }
        format.json { render :show, status: :ok, location: @treasure }

        #broadcast @treasure, "updated"
      else
        format.html { render :edit }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /treasures/1
  # DELETE /treasures/1.json
  def destroy
    @treasure.destroy
    respond_to do |format|
      format.html { redirect_to treasures_url, notice: 'Treasure was successfully destroyed.' }
      format.json { head :no_content }
      broadcast @treasure, "created"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treasure
      @treasure = Treasure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def treasure_params
      params.require(:treasure).permit(:name, :lat, :lng, :value, :start, :stop, :num_takers)
    end
end

TrackermanServer/app/helpers/treasures_helper.rb
module TreasuresHelper
end

TrackermanServer/app/views/treasures/_form.html.erb
<%= form_for(@treasure) do |f| %>
  <% if @treasure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treasure.errors.count, "error") %> prohibited this treasure from being saved:</h2>

      <ul>
      <% @treasure.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.number_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.number_field :lng %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start %>
  </div>
  <div class="field">
    <%= f.label :stop %><br>
    <%= f.datetime_select :stop %>
  </div>
  <div class="field">
    <%= f.label :num_takers %><br>
    <%= f.number_field :num_takers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

TrackermanServer/app/views/treasures/edit.html.erb
<h1>Editing Treasure</h1>

<%= render 'form' %>

<%= link_to 'Show', @treasure %> |
<%= link_to 'Back', treasures_path %>

TrackermanServer/app/views/treasures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Treasures</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Value</th>
      <th>Start</th>
      <th>Stop</th>
      <th>Num takers</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @treasures.each do |treasure| %>
      <tr>
        <td><%= treasure.name %></td>
        <td><%= treasure.lat %></td>
        <td><%= treasure.lng %></td>
        <td><%= treasure.value %></td>
        <td><%= treasure.start %></td>
        <td><%= treasure.stop %></td>
        <td><%= treasure.num_takers %></td>
        <td><%= link_to 'Show', treasure %></td>
        <td><%= link_to 'Edit', edit_treasure_path(treasure) %></td>
        <td><%= link_to 'Destroy', treasure, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treasure', new_treasure_path %>





<!-- Uses gem GON to communicate variables between RAILS and JS -->
<!-- See TreasureController, specificallty "gon.treasures = Treasure.all" -->

<div id="map"></div>
<div id="demo"></div>

  <style>
	  #map {
		  width: 100%;
		  height: 400px;
	  }
  </style>

  <script>
	function initMap() {
		var myLatLng = {lat: 60.644, lng: 17.000};

		/* CREATE A MAP! */
		var mapDiv = document.getElementById('map');
		var map = new google.maps.Map(mapDiv, {
			center: myLatLng,
			zoom: 10
		});

		console.log(gon.treasures);

		for(l=0; l<gon.treasures.length; l++) {

			console.log("lat : " + gon.treasures[l].lat + " lng:" + gon.treasures[l].lng);

			var p = {
				'lat': parseFloat(gon.treasures[l].lat),
				'lng': parseFloat(gon.treasures[l].lng)
			};

			var image = 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png';

			var marker = new google.maps.Marker({
				position: p,
				map: map,
				title: gon.treasures[l].name,
				icon: image
			});
 		}

		/*map.addListener('center_changed', function() {
			// 3 seconds after the center of the map has changed, pan back to the
			// marker.
			window.setTimeout(function() {
				map.panTo(marker.getPosition());
			}, 3000);
		}); */

		/* marker.addListener('click', function() {
			map.setZoom(8);
			map.setCenter(marker.getPosition());
		});*/

		map.addListener('click', function(e) {
			placeMarkerAndPanTo(e.latLng, map);
		});

		function placeMarkerAndPanTo(latLng, map) {
			var marker = new google.maps.Marker({
				position: latLng,
				map: map
			});
			map.panTo(latLng);

			informUser(latLng.lat(), latLng.lng());
		}
	}
  </script>

<script async defer
		src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBLrXVDgIBkFlSsRYbzyxKDce9pRIEaekY&callback=initMap">

</script>

<script type="text/javascript">

	var x = document.getElementById("demo");
	function getLocation() {
		if (navigator.geolocation) {
			var geoOptions = {
				maximumAge: 48 * 60 * 1000
			};			navigator.geolocation.getCurrentPosition(successCb, errorCb, geoOptions);
		} else {
			x.innerHTML = "Geolocation is not supported by this browser.";
		}
	}
	function successCb(position) {
		/* x.innerHTML = "Latitude: " + position.coords.latitude +
		"<br>Longitude: " + position.coords.longitude; */
		informUser(position.coords.latitude, position.coords.longitude);


		var latlon = position.coords.latitude + "," + position.coords.longitude;

		var img_url = "http://maps.googleapis.com/maps/api/staticmap?center=" + latlon + "&zoom=14&size=400x300&sensor=false";

		document.getElementById("map").innerHTML = "<img src='"+img_url+"'>";
	}

	function informUser(lat, lng) {
		x.innerHTML = "Lat: " + lat + "Long: " + lng;

	}

	function errorCb(error) {
		switch(error.code) {
			case error.PERMISSION_DENIED:
				x.innerHTML = "User denied the request for Geolocation."
				break;
			case error.POSITION_UNAVAILABLE:
				x.innerHTML = "Location information is unavailable."
				break;
			case error.TIMEOUT:
				x.innerHTML = "The request to get user location timed out."
				break;
			case error.UNKNOWN_ERROR:
				x.innerHTML = "An unknown error occurred."
				break;
		}
	}
	getLocation();


</script>

TrackermanServer/app/views/treasures/new.html.erb
<h1>New Treasure</h1>

<%= render 'form' %>

<%= link_to 'Back', treasures_path %>

TrackermanServer/app/views/treasures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @treasure.name %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @treasure.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @treasure.lng %>
</p>

<p>
  <strong>Value:</strong>
  <%= @treasure.value %>
</p>

<p>
  <strong>Start:</strong>
  <%= @treasure.start %>
</p>

<p>
  <strong>Stop:</strong>
  <%= @treasure.stop %>
</p>

<p>
  <strong>Num takers:</strong>
  <%= @treasure.num_takers %>
</p>

<%= link_to 'Edit', edit_treasure_path(@treasure) %> |
<%= link_to 'Back', treasures_path %>